### ISSUE TITLE
Gunner Arcane Barrage Ghosting after Replenish

### ISSUE THREAD

**Issue by Vicarioux** [pinkipi/skill-prediction#33]
I've noticed that Gunner AB tends to ghost when used directly after replenishment. The first AB goes off and pops perfectly fine whilst the second, the one that is reset by replenishment, does not actually detonate despite the animation for it playing.
SKILL_RETRY_MS and RESPONSE_THRESHOLD have been edited to suit my ping using resource manager and all other skills seem to be working fine at the moment. 240ms player in case that helps with anything.
Should note that the second AB WILL go off and detonate if I wait ~half a second before detonation. No issues with first AB being instantly detonated though.

**Comment by pinkipi** [comment]
Fixed in the latest commit.

After testing with Clumsy at +200ms I realised simulating the abnormality didn't actually cause the client to register the projectile to detonate, so AB needs to remain locked until the client receives that info. As a result, it will still take longer than normal to detonate at very high ping (no known workaround).
