### ISSUE TITLE
Skill Prediction is not compatible with the obsolete mod "cooldowns"

### ISSUE THREAD

**Issue by Samos1r** [pinkipi/skill-prediction#95]
hey i tried the mod and then this happen :
![wdeqeqeqe](https://user-images.githubusercontent.com/16425268/35488112-f9951fa8-04b5-11e8-8dbe-3848abaf97ad.PNG)

can someone provide me a solution, please @_@

**Comment by pinkipi** [comment]
Delete the folder `cooldowns` in `tera-proxy/bin/node_modules` in order to use skill-prediction (which includes improved cooldown prediction) instead. If you moved `cooldowns` to a different folder as a backup then make sure it's **not** in a folder named `node_modules` or else it will still be considered "installed".
